language: rust
rust:
- nightly
- beta
- stable
sudo: false
os:
- linux
cache:
  directories:
  - "$HOME/.cargo"
  - target
env:
  global:
  - secure: "JKijLISIcscFxBB+W4B8lGve3TG5AhZUAojnEJu5p7FelK0vzW+hNBfOXo7OO35MC24w0t+tfEWoiy56NxSr5zJld9rB5owFiPVz47wmhXlKqI7Lu78BsiSnQqhXr8exRiJhOJZM8umD0wOeCw3+cVB1FMmHPxE5pgPM33hJWX/xvlIYeWGcUK/5Z09n/ebg2+gR9wOUyFOHnZu/xqPo2QldtLQ8QTNM2cdWJQnb2qDaPH3tfLgjVq4sTM/4LwMHyXcjLl73KwW4X0skroRBG0Ehkeickmz9ZcX6ol2BXvT6hLngZ4Vc8DOXzuWDcPM+tCYBD0s+8NLy0YIFL/uR4+2ICB0Q1FwPdnHWPD7Z8D1UXFgdQR4Y1tXk6RgqE7KUW2yUmdFqzddzw9PQDBKbgHiB7EDx2ujGnKbty6JiNY8Ja1n7MZ4jFgr8vgyCXRwrV9IW+Wr4gtO3kBPOO1ULYBq7+HLPc4qGN4ENa5wwKPmfqqXgpEZuWu7CNldXDl3IWtZw5YEJBOVBQXStnXkmqa2tIdHUlhDvUdmzxDYS8boavIOgxVlFefzDVIoPp+vfmtxGt5WyjmNV4JyBnTEUVdY1oGQij1ozjcHB50JS3Sl2/RLMpLRzMuiSIwDefTjcCr2kWMO7sBN2WqgH99F01EzM6SPN2rzRxFnvape+eTs="
  - secure: "md8d9M2+90BGgiixH2iIkhsg84TqzyaEX7tShRhBrYx/dPICtQGpChko53ypuZ4I12ZM+39DSnSvzSuYyHa2dBAXtU+uiW3SX0/l50M0heQXpLZcjOqKIk4V8P9w+kHoA0aRYgqCyJQhVKKYEAwg1ZMxcPr3VKpkl9CuvIzUWq2BW9g6+P1U31P2f7yUtB2dHn6v7VKCNNh0X3uDQSmzFZy73DfamaG1pc1Gb3eDScDWhoW6qo7Ucru3j9R0HpzvHV6jbplm+dr6u36sglr5w8gEbZ+4eaJT+ueo7knwCMKk98RBaXciHx3sLNot/DJaou1INjz4Jwm4s3kHGa2SzJG03ALXV/k9EAgJIzluj1uLvt8O19vvhkpc01HmJ01Nbv9S/iLXw7QvyNjfLZW3lvbbq36JNPUSGVSuwAugC1EXIccufMXGa27lVvDIW9n5KUTuKONrfcbmYTEJdpBJb/tEWQb1BU31e8U8vY2Zwu//BMKyugLiSf7pADt5RD+n/U6h+PwBxeJd2dFWVdu1vw86A0iWbfvcu+GT3kFaprh0+UGFfVxA9gDyzTHLIPLRPLYPCqCU6jfq91ODthrpo1QghWf2mKA19KU41YQZMjT6p0NH68vTtcZLh+pnK7/hXT8ttwJAhBoJ/SucgPVqcCDhuXdKTnW08rjtKq9aezk="
before_install:
- curl -L https://github.com/arcnmx/ci/archive/0.1.tar.gz | tar -xzC $HOME && . $HOME/ci-0.1/src
script:
- cargo test
- cargo build
deploy:
  provider: script
  script: 'true'
  on:
    tags: true
    all_branches: true
    condition: "$TRAVIS_RUST_VERSION = stable"
before_deploy:
- cargo doc
- cargo package
after_deploy:
- cargo pages-publish
- cargo publish
